openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8000'
paths:
  /api/user:
    get:
      summary: ''
      operationId: getApiUser
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/oi:
    get:
      summary: ''
      operationId: getApiOi
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: oi
      tags:
        - Endpoints
      security: []
  /api/register:
    post:
      summary: 'Log in the user.'
      operationId: logInTheUser
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "{\n \"access_token\": \"eyJ0eXA...\",\n \"token_type\": \"Bearer\",\n}"
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'The name of the  user.'
                  example: secret
                email:
                  type: string
                  description: 'The email of the  user.'
                  example: testuser@example.com
                password:
                  type: string
                  description: 'The password of the  user.'
                  example: secret
                password_confirmation:
                  type: string
                  description: 'The password of the  user password.'
                  example: secret
              required:
                - name
                - email
                - password
                - password_confirmation
      security: []
tags:
  -
    name: Endpoints
    description: ''
